### ISSUE TITLE
Suggestion: Allow shrinking text

### ISSUE THREAD

**Issue by MrPeteH** [lazyguyy/survivle#9] opened 2022-03-13 04:20 UTC
I got to nine rows and wanted to capture my answer.
But the text size is fixed, so I cannot capture in one screen grab.

It would be nice if standard shrink/grow methods were allowed.

**Comment by lazyguyy** [comment] 2022-03-13 16:23
That is a good suggestion. I don't know exactly how to approach this, but I have a few ideas in mind. I will try to implement them soon but I'm currently a bit busy.

**Comment by lazyguyy** [comment] 2024-07-14 21:30
Duplicate of #17 and (hopefully) fixed anyway

**Closed as completed by lazyguyy** 2024-07-14 21:30 UTC
Labels: enhancement
